name: eike_frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.0.0
  drift: ^2.0.2+1
  sqlite3: ">=1.8.0 <3.0.0"
  sqlcipher_flutter_libs: ^0.6.0
  flutter_secure_storage: ^10.0.0
  path: ^1.9.0
  path_provider: ^2.1.0
  provider: ^6.1.5+1
  local_auth: ^3.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  http: ^1.2.0
  archive: ^3.6.1
  yaml: ^3.1.2
  drift_dev: ^2.0.2
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/content/
    - assets/content/7-things/
    - assets/fonts/Inter-license.txt
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#3a78b8"
  adaptive_icon_foreground: "assets/icon/eike_app_logo_2.png"
  adaptive_icon_foreground_inset: 16
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/eike_app_logo_blue_bg_3.png"
  # TODO: adjust min_sdk_android and rerun after setting min sdk for build
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/eike_app_logo_blue_bg_3.png"
    background_color: "#3a78b8"
    theme_color: "#3a78b8"
