appId: com.example.eike_frontend

# Welche Flows sollen standardmäßig ausgeführt werden?
flows:
  - "flows/*/*.yaml"   # alle Flows in Feature-Unterordnern, z.B. flows/home/home_smoke.yaml

# Pfad für Artefakte (Screenshots, Logs, AI-Reports)
testOutputDir: ".maestro/tests" # default